version: '2'
services:
  survey-front:
    image: survey-front
    ports:
      - 80:80
    depends_on:
      - survey-rest
  survey-rest:
    mem_limit: 2048m
    image: survey-rest
    environment:
      DATABASE_HOST: survey-db
      DATABASE_USER: dbuser
      DATABASE_PASSWORD: dbp4ss
      DATABASE_NAME: demo
      DATABASE_PORT: 3306
    ports:
      - 8080:8080
    depends_on:
      - survey-db
  survey-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: p4SSW0rd
      MYSQL_DATABASE: demo
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss
